### PR TITLE
[#125] [Chore] Update SurveyDropdownQuestionScreen to be able to preview

### LINKED ISSUE #125: [Chore] Update SurveyDropdownQuestionScreen to be able to preview
## Why

Currently, `SurveyDropdownQuestionScreen` has an error in `Preview`. Fix the error of `Preview` so that the developer can see the preview.

## Who Benefits?

Developer

### PR DESCRIPTION
**Pull request by kaungkhantsoe**
Closes #125 

## What happened 👀

Currently, SurveyDropdownQuestionScreen has an error in Preview. Fix the error of Preview so that the developer can see the preview.

## Insight 📝

Calling `SurveyDropdownQuestionScreen with empty list cause the `IndexOutOfBound` error and causing the preview rendering error. So calling with a valid amount of list of `SurveyAnswer` fixed the issue

## Proof Of Work 📹
Screen Shot 2022-10-27 at 3 32 40 PM

### CODE REVIEW

**Review by AVI5HEK — APPROVED** [review]

**Comment by ryan-conway** [comment]
@kaungkhantsoe If using an empty list causes an error, surely we should fix the error instead of fixing the preview? 🤔

**Comment by kaungkhantsoe** [comment]
> @kaungkhantsoe If using an empty list causes an error, surely we should fix the error instead of fixing the preview? 🤔

Updated @ryan-conway

**Comment by ryan-conway** [comment]
@kaungkhantsoe LGTM but one of the tests failed 🤔

**Comment by kaungkhantsoe** [comment]
@ryan-conway Fixed 👍

**Review by ryan-conway — APPROVED** [review]

**Pull request merged**
